export const ErrorCodes = {
  // Auth
  AUTH_TOKEN_MISSING:        'AUTH_TOKEN_MISSING',
  AUTH_PAYLOAD_MALFORMED:    'AUTH_PAYLOAD_MALFORMED',
  AUTH_SESSION_EXPIRED:      'AUTH_SESSION_EXPIRED',
  // Capacity
  CAPACITY_LIMIT_EXCEEDED:   'CAPACITY_LIMIT_EXCEEDED',
  // Materials
  MATERIAL_PHOTO_REQUIRED:   'MATERIAL_PHOTO_REQUIRED',
  MATERIAL_DELTA_ZERO:       'MATERIAL_DELTA_ZERO',
  // Measurements
  MEASUREMENT_ORDER_LOCKED:  'MEASUREMENT_ORDER_LOCKED',
  // Orders
  ORDER_EVENT_DATE_REQUIRED: 'ORDER_EVENT_DATE_REQUIRED',
  ORDER_NOT_FOUND:           'ORDER_NOT_FOUND',
  // Workflow
  WORKFLOW_STAGE_SKIP:       'WORKFLOW_STAGE_SKIP',
  WORKFLOW_INVALID_TRANSITION:'WORKFLOW_INVALID_TRANSITION',
  // General
  TENANT_MISMATCH:           'TENANT_MISMATCH',
  VALIDATION_ERROR:          'VALIDATION_ERROR',
  UNKNOWN_ERROR:             'UNKNOWN_ERROR',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
